"""Tests for the AI/agent tradecraft signature domain logic.

Covers the curated-list scan (:func:`scan_text` / :func:`scan_sources`),
read-only file handling, bounding/aggregation, the HYPOTHESIS-tier epistemic
contract, and the evidence-agnostic invariant (no image-specific literals in
the production signature table).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from findevil_agent import ai_signatures as ai
from findevil_agent.ai_signatures import (
    _SIGNATURE_TABLE,
    CONFIDENCE_TIER,
    DEFAULT_LIMIT,
    LEAD_DISCLAIMER,
    known_categories,
    scan_sources,
    scan_text,
    signature_count,
)


class TestScanText:
    def test_detects_llm_output_boilerplate(self) -> None:
        hits = scan_text(
            "As an AI language model, I cannot assist with that request.",
            source="<inline>",
        )
        ids = {h.signature_id for h in hits}
        assert "llm_output_boilerplate.language_model_persona" in ids
        assert "llm_output_boilerplate.refusal" in ids

    def test_detects_agent_framework_modules(self) -> None:
        hits = scan_text(
            "import langchain_core\nfrom crewai import Agent\nimport autogen",
            source="<inline>",
        )
        ids = {h.signature_id for h in hits}
        assert "agent_framework.langchain" in ids
        assert "agent_framework.crewai" in ids
        assert "agent_framework.autogen" in ids

    def test_detects_react_scratchpad(self) -> None:
        trace = "Thought: I should look\nAction: search\nAction Input: foo\nObservation: bar"
        hits = scan_text(trace, source="<inline>")
        assert any(h.signature_id == "agent_scratchpad.react" for h in hits)

    def test_detects_llm_api_client(self) -> None:
        hits = scan_text(
            "POST https://api.openai.com/v1/chat/completions\nimport openai",
            source="<inline>",
        )
        ids = {h.signature_id for h in hits}
        assert "llm_api_client.openai_endpoint" in ids
        assert "llm_api_client.sdk_import" in ids

    def test_detects_model_family_identifier(self) -> None:
        hits = scan_text('"model": "gpt-4-turbo"', source="<inline>")
        assert any(h.signature_id == "llm_model_identifier.family" for h in hits)

    def test_no_match_on_benign_text(self) -> None:
        hits = scan_text(
            "The scheduled task pointed at a user-writable binary in System32.",
            source="<inline>",
        )
        assert hits == []

    def test_framework_lookaheads_avoid_common_word_false_positives(self) -> None:
        # The framework patterns drop the trailing word boundary so module
        # suffixes match; the (?![a-z]) guard must keep them off ordinary English.
        benign = (
            "The report was auto-generated and autogenerated nightly. "
            "The flight crew aircraft logbook was reviewed."
        )
        hits = scan_text(benign, source="<inline>")
        assert hits == []

    def test_framework_module_suffixes_still_match(self) -> None:
        text = "import autogen_agentchat\nfrom crewai_tools import X\nimport llama_index.core"
        ids = {h.signature_id for h in scan_text(text, source="<inline>")}
        assert "agent_framework.autogen" in ids
        assert "agent_framework.crewai" in ids
        assert "agent_framework.llama_index" in ids

    def test_match_is_case_insensitive(self) -> None:
        hits = scan_text("AS AN AI LANGUAGE MODEL", source="<inline>")
        assert any(h.signature_id == "llm_output_boilerplate.language_model_persona" for h in hits)

    def test_aggregates_occurrences_with_first_offset(self) -> None:
        text = "filler langchain more text langchain end"
        hits = [h for h in scan_text(text, source="src") if h.category == "agent_framework"]
        assert len(hits) == 1
        assert hits[0].occurrences == 2
        assert hits[0].first_offset == text.index("langchain")

    def test_category_filter_restricts_evaluation(self) -> None:
        text = "import langchain\nas an ai language model"
        only_framework = scan_text(text, source="s", categories=frozenset({"agent_framework"}))
        assert {h.category for h in only_framework} == {"agent_framework"}

    def test_preview_is_whitespace_collapsed_and_bounded(self) -> None:
        text = "noise\n\n   import   openai   \n\nmore"
        hits = scan_text(text, source="s", preview_chars=40)
        match = next(h for h in hits if h.signature_id == "llm_api_client.sdk_import")
        assert "\n" not in match.preview
        assert "  " not in match.preview

    def test_repetitive_adversarial_text_counts_without_match_materialization(self) -> None:
        text = "langchain " * 100_000
        hit = next(h for h in scan_text(text, source="s") if h.signature_id.endswith(".langchain"))
        assert hit.occurrences == 100_000


class TestScanSources:
    def test_inline_only(self) -> None:
        scan = scan_sources(text="import langchain")
        assert scan.sources_scanned == 1
        assert scan.read_errors == ()
        assert any(h.source == "<inline>" for h in scan.hits)

    def test_reads_file_path_read_only(self, tmp_path: Path) -> None:
        artifact = tmp_path / "recovered.py"
        artifact.write_text("from anthropic import Anthropic\n# you are a helpful assistant")
        before = artifact.read_bytes()
        scan = scan_sources(paths=(str(artifact),))
        # File content is untouched (read-only).
        assert artifact.read_bytes() == before
        ids = {h.signature_id for h in scan.hits}
        assert "llm_api_client.sdk_import" in ids
        assert "prompt_scaffold.helpful_assistant" in ids
        assert all(h.source == str(artifact) for h in scan.hits)

    def test_missing_file_is_soft_error_not_raise(self, tmp_path: Path) -> None:
        scan = scan_sources(paths=(str(tmp_path / "nope.txt"),))
        assert scan.hits == ()
        assert len(scan.read_errors) == 1
        assert "not found" in scan.read_errors[0]

    def test_directory_path_is_soft_error(self, tmp_path: Path) -> None:
        scan = scan_sources(paths=(str(tmp_path),))
        assert len(scan.read_errors) == 1
        assert "is a directory" in scan.read_errors[0]

    def test_limit_truncates(self) -> None:
        text = "import langchain\nimport openai\nas an ai language model"
        scan = scan_sources(text=text, limit=1)
        assert len(scan.hits) == 1
        assert scan.truncated is True

    def test_requires_no_source_returns_empty(self) -> None:
        # Domain layer tolerates no-source (the shim enforces at-least-one);
        # this documents the pure function's behavior.
        scan = scan_sources()
        assert scan.hits == ()
        assert scan.sources_scanned == 0

    def test_signatures_evaluated_reflects_category_filter(self) -> None:
        full = scan_sources(text="x")
        filtered = scan_sources(text="x", categories=frozenset({"agent_framework"}))
        assert full.signatures_evaluated == signature_count()
        assert 0 < filtered.signatures_evaluated < full.signatures_evaluated

    def test_aggregate_byte_budget_stops_before_scanning_remaining_paths(
        self, tmp_path: Path
    ) -> None:
        paths = []
        for index in range(4):
            path = tmp_path / f"{index}.txt"
            path.write_bytes(b"abcdefgh")
            paths.append(str(path))

        scan = scan_sources(paths=tuple(paths), byte_limit=16)
        assert scan.bytes_scanned == 16
        assert scan.paths_considered == 2
        assert scan.sources_skipped == 2
        assert scan.truncated is True
        assert scan.truncation_reason == "aggregate_byte_limit"

    def test_domain_path_cap_prevents_unbounded_file_policy_work(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr(ai, "MAX_PATHS", 2)
        paths = []
        for index in range(3):
            path = tmp_path / f"{index}.txt"
            path.write_text("benign")
            paths.append(str(path))

        scan = scan_sources(paths=tuple(paths))
        assert scan.paths_requested == 3
        assert scan.paths_considered == 2
        assert scan.sources_skipped == 1
        assert scan.truncation_reason == "path_limit"


class TestEpistemicContract:
    def test_confidence_tier_is_hypothesis(self) -> None:
        assert CONFIDENCE_TIER == "HYPOTHESIS"

    def test_lead_disclaimer_states_lead_only(self) -> None:
        lowered = LEAD_DISCLAIMER.lower()
        assert "hypothesis" in lowered
        assert "lead" in lowered
        assert "never" in lowered

    def test_default_limit_positive(self) -> None:
        assert DEFAULT_LIMIT > 0


class TestEvidenceAgnostic:
    """The curated table must key on general patterns, not one image."""

    # Tokens that would couple the signature list to a specific evidence image.
    _IMAGE_SPECIFIC_TOKENS = (
        "mr. evil",
        "mr evil",
        "mr-evil",
        "schardt",
        "nhc-",
    )

    def test_signature_ids_and_patterns_have_no_image_literals(self) -> None:
        for sig in _SIGNATURE_TABLE:
            blob = f"{sig.signature_id} {sig.pattern} {sig.description}".lower()
            for token in self._IMAGE_SPECIFIC_TOKENS:
                assert token not in blob, f"{sig.signature_id} leaks image literal {token!r}"

    def test_signature_ids_are_unique(self) -> None:
        ids = [s.signature_id for s in _SIGNATURE_TABLE]
        assert len(ids) == len(set(ids))

    def test_signature_id_prefix_matches_category(self) -> None:
        for sig in _SIGNATURE_TABLE:
            assert sig.signature_id.startswith(f"{sig.category}.")

    def test_known_categories_are_sorted_and_nonempty(self) -> None:
        cats = known_categories()
        assert cats == tuple(sorted(cats))
        assert len(cats) >= 1
