"""Stdio JSON-RPC client for the findevil-mcp Rust server.

Spec #2 §3 + §6. The Python agent spawns the Rust binary as a
subprocess and exchanges line-delimited JSON-RPC 2.0 requests over
stdin/stdout. Each ``call_tool(name, args)`` returns the tool's
typed output plus a SHA-256 of the raw output bytes — the latter
becomes a Merkle leaf for M2.

Design decisions:

  * Synchronous API. The agent runtime is mostly async but every
    LangGraph node is invoked from a sync context too; a sync
    client with internal threading is the simpler primitive.
    Async wrappers can be added in a follow-up.
  * ``McpClient`` is a Protocol; ``StdioMcpClient`` is the real
    impl; ``MockMcpClient`` is the test impl. Tests never spawn
    real binaries.
  * Tool-call IDs are UUID4 generated in the client. The server
    echoes them on responses so the audit trail can correlate.

Wire format (per MCP spec):

  Request line:   ``{"jsonrpc":"2.0","id":N,"method":"tools/call",
                     "params":{"name":TOOL,"arguments":{...}}}\\n``

  Response line:  ``{"jsonrpc":"2.0","id":N,"result":{
                     "content":[{"type":"text","text":STRINGIFIED_JSON}],
                     "_meta":{...}}}\\n``

  Error line:     ``{"jsonrpc":"2.0","id":N,"error":{
                     "code":N,"message":"...","data":{...}}}\\n``
"""

from __future__ import annotations

import contextlib
import hashlib
import json
import os
import signal
import subprocess
import threading
import time
import uuid
from collections import deque
from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, NoReturn, Protocol

_MCP_STDOUT_FRAME_MAX_BYTES = 64 * 1024 * 1024
_MCP_STDERR_LINE_MAX_BYTES = 64 * 1024
_MCP_STDERR_RETAIN_MAX_BYTES = 4096
_PROCESS_REAP_TIMEOUT_S = 1.0
_READER_JOIN_TIMEOUT_S = 0.5


class McpClientError(RuntimeError):
    """Generic client failure — pre-RPC-layer issues (subprocess
    crashed, JSON malformed, etc.)."""


class McpRpcError(RuntimeError):
    """Server returned a JSON-RPC error response. ``code`` and
    ``data`` come from the response envelope."""

    def __init__(self, code: int, message: str, data: Any | None = None) -> None:
        super().__init__(message)
        self.code = code
        self.data = data


@dataclass(frozen=True)
class ToolCallResult:
    """Outcome of a single ``call_tool``.

    ``raw_output_text`` is the verbatim ``content[0].text`` string
    the server emitted. ``parsed`` is its ``json.loads`` if it
    parses; otherwise None and the raw text remains the source of
    truth for the M2 layer.
    """

    tool_call_id: str
    """UUID4 generated by the client; quoted in audit log."""

    tool_name: str
    raw_output_text: str
    output_sha256: str
    parsed: dict[str, Any] | None
    meta: dict[str, Any] = field(default_factory=dict)
    """``_meta`` from the response envelope (Spec #2 §6 — MCP Apps
    widget pointers live here as ``_meta.ui.resourceUri``)."""

    wall_clock_ms: int = 0


class McpClient(Protocol):
    """The face the agent layer depends on."""

    def call_tool(self, tool_name: str, arguments: dict[str, Any]) -> ToolCallResult: ...

    def close(self) -> None: ...


# ---------------------------------------------------------------------------
# StdioMcpClient — spawns + drives the real Rust binary.
# ---------------------------------------------------------------------------


class StdioMcpClient:
    """Production client over stdio JSON-RPC.

    Usage:
        client = StdioMcpClient(["/usr/local/bin/findevil-mcp"])
        result = client.call_tool("evtx_query", {"case_id": "c", "evtx_path": "x"})
        client.close()

    Or via a context manager:
        with StdioMcpClient([...]) as client:
            ...
    """

    _next_id: int

    def __init__(
        self,
        command: list[str],
        *,
        cwd: Path | None = None,
        env: dict[str, str] | None = None,
        startup_timeout_s: float = 5.0,
        request_timeout_s: float = 120.0,
        abort_callback: Callable[[], None] | None = None,
    ) -> None:
        self._command = list(command)
        self._cwd = cwd
        self._env = env
        self._startup_timeout_s = startup_timeout_s
        self._request_timeout_s = request_timeout_s
        self._abort_callback = abort_callback
        self._abort_callback_called = False
        self._abort_lock = threading.Lock()
        self._proc: subprocess.Popen[bytes] | None = None
        self._stdout_reader_thread: threading.Thread | None = None
        self._stderr_thread: threading.Thread | None = None
        self._lock = threading.Lock()
        self._next_id = 1
        self._closed = False
        self._stderr_tail: deque[str] = deque(maxlen=200)

    # --- lifecycle ---

    def __enter__(self) -> StdioMcpClient:
        self._ensure_started()
        return self

    def __exit__(self, *_: object) -> None:
        self.close()

    def _ensure_started(self) -> None:
        if self._proc is not None:
            return
        try:
            self._proc = subprocess.Popen(
                self._command,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                cwd=str(self._cwd) if self._cwd else None,
                env=self._env,
                **self._process_group_options(),
            )
        except FileNotFoundError as exc:
            raise McpClientError(f"could not spawn MCP server {self._command!r}: {exc}") from exc
        self._stderr_thread = threading.Thread(target=self._drain_stderr, daemon=True)
        self._stderr_thread.start()

    @staticmethod
    def _process_group_options() -> dict[str, Any]:
        if os.name == "posix":
            return {"start_new_session": True}
        if os.name == "nt":
            return {"creationflags": getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0)}
        return {}

    def _drain_stderr(self) -> None:
        proc = self._proc
        if proc is None or proc.stderr is None:
            return
        discarding_oversize_line = False
        try:
            while True:
                line = proc.stderr.readline(_MCP_STDERR_LINE_MAX_BYTES + 1)
                if line == b"":
                    return
                terminated = line.endswith(b"\n")
                if discarding_oversize_line:
                    if terminated:
                        discarding_oversize_line = False
                    continue
                if len(line) > _MCP_STDERR_LINE_MAX_BYTES:
                    retained_bytes = line[:_MCP_STDERR_RETAIN_MAX_BYTES].rstrip(b"\r\n")
                    retained = retained_bytes.decode("utf-8", errors="replace")
                    self._stderr_tail.append(f"{retained} [truncated]")
                    discarding_oversize_line = not terminated
                    continue
                retained_bytes = line[:_MCP_STDERR_RETAIN_MAX_BYTES].rstrip(b"\r\n")
                retained = retained_bytes.decode("utf-8", errors="replace")
                if len(line.rstrip(b"\r\n")) > _MCP_STDERR_RETAIN_MAX_BYTES:
                    retained = f"{retained} [truncated]"
                self._stderr_tail.append(retained)
        except (ValueError, OSError):
            return

    def _abort_transport(self) -> None:
        self._closed = True
        proc = self._proc
        if proc is not None:
            self._terminate_process_tree(proc)
            self._reap_process(proc)
            self._join_reader_threads()
        callback: Callable[[], None] | None = None
        with self._abort_lock:
            if not self._abort_callback_called:
                self._abort_callback_called = True
                callback = self._abort_callback
        if callback is not None:
            with contextlib.suppress(Exception):
                callback()
        if proc is not None:
            self._close_process_streams(proc)

    @staticmethod
    def _terminate_process_tree(proc: subprocess.Popen[bytes]) -> None:
        if os.name == "posix":
            try:
                os.killpg(proc.pid, signal.SIGKILL)
                return
            except (OSError, ProcessLookupError):
                pass
        elif os.name == "nt":
            try:
                completed = subprocess.run(
                    ["taskkill", "/PID", str(proc.pid), "/T", "/F"],
                    stdin=subprocess.DEVNULL,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    timeout=_PROCESS_REAP_TIMEOUT_S,
                    check=False,
                )
                if completed.returncode == 0:
                    return
            except (FileNotFoundError, OSError, subprocess.TimeoutExpired):
                pass
            ctrl_break = getattr(signal, "CTRL_BREAK_EVENT", None)
            if ctrl_break is not None:
                with contextlib.suppress(OSError):
                    proc.send_signal(ctrl_break)
        with contextlib.suppress(OSError):
            proc.kill()

    @staticmethod
    def _reap_process(proc: subprocess.Popen[bytes]) -> None:
        try:
            proc.wait(timeout=_PROCESS_REAP_TIMEOUT_S)
        except subprocess.TimeoutExpired:
            with contextlib.suppress(OSError):
                proc.kill()
            with contextlib.suppress(subprocess.TimeoutExpired):
                proc.wait(timeout=_PROCESS_REAP_TIMEOUT_S)

    def _join_reader_threads(self) -> None:
        deadline = time.monotonic() + _READER_JOIN_TIMEOUT_S
        current = threading.current_thread()
        for thread in (self._stdout_reader_thread, self._stderr_thread):
            if thread is None or thread is current or not thread.is_alive():
                continue
            thread.join(timeout=max(0.0, deadline - time.monotonic()))

    def _close_process_streams(self, proc: subprocess.Popen[bytes]) -> None:
        streams = (
            (proc.stdin, None),
            (proc.stdout, self._stdout_reader_thread),
            (proc.stderr, self._stderr_thread),
        )
        for stream, reader in streams:
            if stream is None or stream.closed:
                continue
            # BufferedReader.close() waits on its internal lock. If a failed
            # platform-specific tree kill left a reader blocked on an inherited
            # pipe, skip that descriptor rather than blocking cleanup/callbacks.
            if reader is not None and reader.is_alive():
                continue
            with contextlib.suppress(OSError):
                stream.close()

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        if self._proc is None:
            return
        proc = self._proc
        if proc.stdin and not proc.stdin.closed:
            with contextlib.suppress(Exception):  # nosec - best effort
                proc.stdin.close()
        self._terminate_process_tree(proc)
        self._reap_process(proc)
        self._join_reader_threads()
        self._close_process_streams(proc)

    # --- core call ---

    def call_tool(self, tool_name: str, arguments: dict[str, Any]) -> ToolCallResult:
        """Send one ``tools/call`` and parse the response.

        Thread-safe. Raises ``McpClientError`` on transport failure,
        ``McpRpcError`` on server-side error.
        """
        if self._closed:
            raise McpClientError("client is closed")
        with self._lock:
            self._ensure_started()
            assert self._proc is not None
            assert self._proc.stdin is not None
            assert self._proc.stdout is not None

            request_id = self._next_id
            self._next_id += 1
            tool_call_id = str(uuid.uuid4())
            request = {
                "jsonrpc": "2.0",
                "id": request_id,
                "method": "tools/call",
                "params": {"name": tool_name, "arguments": arguments},
            }
            line = (json.dumps(request, separators=(",", ":")) + "\n").encode("utf-8")
            started = time.monotonic()
            try:
                self._proc.stdin.write(line)
                self._proc.stdin.flush()
            except (BrokenPipeError, OSError) as exc:
                self._abort_transport()
                raise McpClientError(f"MCP stdin write failed: {exc}") from exc

            response_line = self._read_line_with_timeout()
            wall_ms = int((time.monotonic() - started) * 1000)

            try:
                response = json.loads(response_line)
            except (json.JSONDecodeError, RecursionError) as exc:
                self._abort_transport()
                raise McpClientError(
                    f"MCP server returned non-JSON line: {response_line[:200]!r}"
                ) from exc
            if not isinstance(response, dict):
                self._raise_protocol_error("MCP server returned a non-object JSON-RPC envelope")
            if response.get("jsonrpc") != "2.0":
                self._raise_protocol_error("MCP server returned an invalid JSON-RPC version")
            response_id = response.get("id")
            if isinstance(response_id, bool) or response_id != request_id:
                self._raise_protocol_error("MCP server returned a mismatched JSON-RPC id")
            has_result = "result" in response
            has_error = "error" in response
            if has_result == has_error:
                self._raise_protocol_error(
                    "MCP server response must contain exactly one result or error"
                )

            return self._parse_response(
                response=response,
                tool_call_id=tool_call_id,
                tool_name=tool_name,
                wall_ms=wall_ms,
            )

    # --- helpers ---

    def _read_line_with_timeout(self) -> str:
        """Read a single line with a per-request wall-clock budget.

        We don't have signal-based timeouts on Windows; instead spawn
        the read on a thread and join. Cheap because each call only
        waits for one response line.
        """
        assert self._proc is not None
        assert self._proc.stdout is not None
        result: dict[str, bytes | str] = {}

        def reader() -> None:
            try:
                ln = self._proc.stdout.readline(  # type: ignore[union-attr]
                    _MCP_STDOUT_FRAME_MAX_BYTES + 1
                )
                if len(ln) > _MCP_STDOUT_FRAME_MAX_BYTES:
                    result["error"] = "JSON-RPC response exceeded the 64 MiB frame limit"
                elif ln and not ln.endswith(b"\n"):
                    result["error"] = "server emitted an unterminated JSON-RPC frame"
                else:
                    result["line"] = ln
            except Exception as exc:
                result["error"] = repr(exc)

        thread = threading.Thread(target=reader, daemon=True)
        self._stdout_reader_thread = thread
        thread.start()
        thread.join(timeout=self._request_timeout_s)
        if thread.is_alive():
            self._abort_transport()
            raise McpClientError(f"MCP request timed out after {self._request_timeout_s}s")
        self._stdout_reader_thread = None
        if "error" in result:
            self._abort_transport()
            error = result["error"]
            assert isinstance(error, str)
            raise McpClientError(f"MCP read error: {error}")
        line = result.get("line", b"")
        if not line:
            self._abort_transport()
            raise McpClientError("MCP server closed stdout before responding")
        assert isinstance(line, bytes)
        try:
            return line.rstrip(b"\r\n").decode("utf-8")
        except UnicodeDecodeError as exc:
            self._abort_transport()
            raise McpClientError("MCP server returned invalid UTF-8") from exc

    def _raise_protocol_error(self, message: str) -> NoReturn:
        self._abort_transport()
        raise McpClientError(message)

    def _parse_response(
        self,
        *,
        response: dict[str, Any],
        tool_call_id: str,
        tool_name: str,
        wall_ms: int,
    ) -> ToolCallResult:
        if "error" in response:
            err = response["error"]
            if not isinstance(err, dict):
                self._raise_protocol_error("MCP server returned an invalid error object")
            code = err.get("code", -1)
            message = err.get("message", "<no message>")
            if isinstance(code, bool) or not isinstance(code, int):
                self._raise_protocol_error("MCP server returned an invalid error code")
            if not isinstance(message, str):
                self._raise_protocol_error("MCP server returned an invalid error message")
            raise McpRpcError(
                code=code,
                message=message,
                data=err.get("data"),
            )
        result = response.get("result")
        if not isinstance(result, dict):
            self._raise_protocol_error("MCP server returned an invalid result object")
        content = result.get("content")
        if not isinstance(content, list):
            self._raise_protocol_error("MCP server returned invalid result content")
        text = ""
        if content:
            first = content[0]
            if not isinstance(first, dict) or not isinstance(first.get("text"), str):
                self._raise_protocol_error("MCP server returned invalid result content")
            text = first["text"]
        meta = result.get("_meta", {})
        if not isinstance(meta, dict):
            self._raise_protocol_error("MCP server returned invalid result metadata")
        sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
        parsed: dict[str, Any] | None = None
        try:
            obj = json.loads(text)
            if isinstance(obj, dict):
                parsed = obj
        except (json.JSONDecodeError, RecursionError):
            parsed = None
        return ToolCallResult(
            tool_call_id=tool_call_id,
            tool_name=tool_name,
            raw_output_text=text,
            output_sha256=sha,
            parsed=parsed,
            meta=meta,
            wall_clock_ms=wall_ms,
        )


# ---------------------------------------------------------------------------
# MockMcpClient — used by tests.
# ---------------------------------------------------------------------------


class MockMcpClient:
    """Test client that returns canned responses keyed by tool name.

    ``register(tool_name, handler)`` accepts a callable
    ``(arguments) -> dict | str`` that produces the result. dicts
    get JSON-serialized; strings are returned verbatim.

    Records all calls in ``calls`` for assertion.
    """

    def __init__(self) -> None:
        self._handlers: dict[str, Any] = {}
        self.calls: list[tuple[str, dict[str, Any], ToolCallResult]] = []

    def register(self, tool_name: str, handler: Any) -> None:
        self._handlers[tool_name] = handler

    def call_tool(self, tool_name: str, arguments: dict[str, Any]) -> ToolCallResult:
        if tool_name not in self._handlers:
            raise McpRpcError(
                code=-32601,  # JSON-RPC method-not-found code
                message=f"mock has no handler registered for {tool_name!r}",
            )
        handler = self._handlers[tool_name]
        produced = handler(arguments) if callable(handler) else handler

        if isinstance(produced, dict):
            text = json.dumps(produced, sort_keys=True, separators=(",", ":"))
        elif isinstance(produced, str):
            text = produced
        else:
            text = json.dumps({"value": produced}, sort_keys=True, separators=(",", ":"))

        sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
        parsed: dict[str, Any] | None
        try:
            parsed_obj = json.loads(text)
            parsed = parsed_obj if isinstance(parsed_obj, dict) else None
        except json.JSONDecodeError:
            parsed = None

        result = ToolCallResult(
            tool_call_id=str(uuid.uuid4()),
            tool_name=tool_name,
            raw_output_text=text,
            output_sha256=sha,
            parsed=parsed,
            meta={},
            wall_clock_ms=0,
        )
        self.calls.append((tool_name, dict(arguments), result))
        return result

    def close(self) -> None:
        pass


__all__ = [
    "McpClient",
    "McpClientError",
    "McpRpcError",
    "MockMcpClient",
    "StdioMcpClient",
    "ToolCallResult",
]
