#!/usr/bin/env bash
# Curated process environments for evidence-facing MCP servers.
# Source only after project-env.sh has established contained HOME/TMP/XDG paths.

mcp_env_add_if_set() {
  local name value
  for name in "$@"; do
    value="${!name-}"
    [[ -n "${value}" ]] && MCP_CHILD_ENV+=("${name}=${value}")
  done
  return 0
}

mcp_env_base() {
  MCP_CHILD_ENV=()
  mcp_env_add_if_set \
    HOME USER USERPROFILE PATH LANG LC_ALL TZ \
    TMPDIR TMP TEMP XDG_DATA_HOME XDG_STATE_HOME XDG_CACHE_HOME \
    FINDEVIL_HOME CARGO_HOME RUSTUP_HOME UV_CACHE_DIR UV_PYTHON_INSTALL_DIR
}

mcp_rust_child_env() {
  mcp_env_base
  mcp_env_add_if_set \
    AUSEARCH_BIN CHAINSAW_BIN EWF_MOUNT_BIN EZTOOLS_DIR \
    HAYABUSA_BIN HAYABUSA_RULES_BASE FINDEVIL_HAYABUSA_RULE_SET \
    INDXPARSE_BIN JOURNALCTL_BIN LAST_BIN \
    MAC_APT NFDUMP_BIN PLASO_DIR SURICATA_BIN TSHARK_BIN VOLATILITY_BIN \
    FINDEVIL_BULK_EXTRACTOR_BIN FINDEVIL_BULK_KEYWORD_FILE \
    FINDEVIL_ESEDBEXPORT_BIN FINDEVIL_FLS_BIN FINDEVIL_HASHSET_DIR \
    FINDEVIL_HASHSET_MAX_SETS FINDEVIL_HASHSET_MAX_FILE_BYTES \
    FINDEVIL_HASHSET_MAX_TOTAL_BYTES FINDEVIL_HASHSET_MAX_LINE_BYTES \
    FINDEVIL_HASHSET_SQLITE_MAX_OPS FINDEVIL_HASHSET_SQLITE_MAX_FIELD_BYTES \
    FINDEVIL_HASHSET_SQLITE_HEAP_MAX_BYTES \
    FINDEVIL_ICAT_BIN FINDEVIL_INJECTION_LEDGER FINDEVIL_MMLS_BIN \
    FINDEVIL_MOUNT_BIN FINDEVIL_PFFEXPORT_BIN FINDEVIL_UMOUNT_BIN \
    FINDEVIL_VSHADOWINFO_BIN FINDEVIL_VSHADOWMOUNT_BIN \
    FINDEVIL_FLS_TIMEOUT_SECONDS FINDEVIL_ICAT_TIMEOUT_SECONDS \
    FINDEVIL_MMLS_TIMEOUT_SECONDS \
    FINDEVIL_AUSEARCH_TIMEOUT_SECS FINDEVIL_JOURNALCTL_TIMEOUT_SECS \
    FINDEVIL_LOGIN_ACCOUNTING_TIMEOUT_SECS FINDEVIL_NFDUMP_TIMEOUT_SECS \
    FINDEVIL_INDX_TIMEOUT_SECS FINDEVIL_EZ_PARSE_TIMEOUT_SECS \
    FINDEVIL_SURICATA_TIMEOUT_SECS FINDEVIL_PST_TIMEOUT_SECS \
    FINDEVIL_SRUM_TIMEOUT_SECS FINDEVIL_BULK_EXTRACT_TIMEOUT_SECS \
    FINDEVIL_HAYABUSA_TIMEOUT_SECS FINDEVIL_HAYABUSA_OUTPUT_MAX_BYTES \
    FINDEVIL_VSS_TIMEOUT_SECS \
    FINDEVIL_MAC_TRIAGE_TIMEOUT_SECS \
    FINDEVIL_CLOUD_AUDIT_MAX_INPUT_BYTES \
    FINDEVIL_CLOUD_AUDIT_MAX_OUTPUT_BYTES \
    FINDEVIL_CLOUD_AUDIT_MAX_RECORD_BYTES FINDEVIL_PCAP_TIMEOUT_SECS \
    FINDEVIL_SUBPROCESS_STDERR_MAX_BYTES \
    FINDEVIL_SUBPROCESS_STDOUT_MAX_BYTES \
    FINDEVIL_PLASO_TIMEOUT_SECS \
    FINDEVIL_VOL_TIMEOUT_SECS \
    FIND_EVIL_MEMORY_YARA_RULES FIND_EVIL_DISK_YARA_RULES \
    FINDEVIL_YARA_RULES_ROOT \
    FINDEVIL_CASE_OPEN_BINDING \
    FINDEVIL_OUTPUT_ROUTE FINDEVIL_ACKNOWLEDGE_PARSED_EVIDENCE_EGRESS \
    FINDEVIL_BROWSER_CASE_BINDING FINDEVIL_BROWSER_DB_MAX_BYTES \
    FINDEVIL_BROWSER_FIELD_MAX_BYTES FINDEVIL_BROWSER_SQLITE_MAX_OPS \
    FINDEVIL_BROWSER_OUTPUT_MAX_BYTES FINDEVIL_BROWSER_SQLITE_HEAP_MAX_BYTES \
    FINDEVIL_BROWSER_SCHEMA_MAX_ENTRIES
  return 0
}

mcp_python_child_env() {
  mcp_env_base
  mcp_env_add_if_set \
    FINDEVIL_ALLOW_STUB_SIGNER FINDEVIL_EXPERT_MISS_LEDGER \
    FINDEVIL_INJECTION_LEDGER FINDEVIL_LOG_LEVEL FINDEVIL_MEMORY_STORE \
    FINDEVIL_MISS_GH_ENABLED FINDEVIL_MISS_GH_REDACT \
    FINDEVIL_SIGNER FINDEVIL_SIGNING_KEY \
    FINDEVIL_SIGSTORE_EXPECTED_IDENTITY FINDEVIL_SIGSTORE_EXPECTED_ISSUER \
    SIGSTORE_ID_TOKEN \
    FINDEVIL_CUSTODY_BOUNDARY FINDEVIL_ACTIVE_CASE_DIR FINDEVIL_ACTIVE_CASE_ID \
    FINDEVIL_ACTIVE_RUN_ID FINDEVIL_ACTIVE_STARTED_AT FINDEVIL_ACTIVE_SIGNER \
    FINDEVIL_CONTROLLER_CAPABILITY FINDEVIL_CASE_OPEN_BINDING \
    FINDEVIL_OUTPUT_ROUTE FINDEVIL_ACKNOWLEDGE_PARSED_EVIDENCE_EGRESS \
    FINDEVIL_REPLAY_TRANSPORT FINDEVIL_REPLAY_DOCKER_CONTAINER \
    FINDEVIL_FLS_TIMEOUT_SECONDS FINDEVIL_ICAT_TIMEOUT_SECONDS \
    FINDEVIL_MMLS_TIMEOUT_SECONDS \
    FIND_EVIL_MEMORY_YARA_RULES FIND_EVIL_DISK_YARA_RULES \
    FINDEVIL_YARA_RULES_ROOT FINDEVIL_HAYABUSA_RULE_SET \
    DOCKER_HOST DOCKER_CONTEXT DOCKER_TLS_VERIFY DOCKER_CERT_PATH \
    FIND_EVIL_REQUIRE_ARTIFACT_REBIND FIND_EVIL_REQUIRE_ASSERTED_VALUES \
    FIND_EVIL_REQUIRE_BENIGN_EVIDENCE FIND_EVIL_REQUIRE_COUNTER_HYPOTHESIS \
    FIND_EVIL_REQUIRE_COUNTER_HYPOTHESIS_FINDING FIND_EVIL_REQUIRE_EXPECTATION \
    FIND_EVIL_REQUIRE_FP_SUPPRESSORS FIND_EVIL_REQUIRE_TOOL_CALL_ID \
    FIND_EVIL_REQUIRE_WHY_NOT_HIGHER \
    FINDEVIL_BROWSER_CASE_BINDING FINDEVIL_BROWSER_DB_MAX_BYTES \
    FINDEVIL_BROWSER_FIELD_MAX_BYTES FINDEVIL_BROWSER_SQLITE_MAX_OPS \
    FINDEVIL_BROWSER_OUTPUT_MAX_BYTES FINDEVIL_BROWSER_SQLITE_HEAP_MAX_BYTES \
    FINDEVIL_BROWSER_SCHEMA_MAX_ENTRIES
  return 0
}
